repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
  # The following dependencies need to be installed for pre-commit
  # 1. Pre-Commit: brew install pre-commit; pre-commit install
  # 2. golangci-lint: brew install golangci-lint
  # go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  # finally
  # touch  .git/hooks/commit-msg
  # echo "go-commitlinter" >> .git/hooks/commit-msg
  # chmod 755 .git/hooks/commit-msg
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint-mod
        args: ["--allow-parallel-runners", "--timeout=30m"]
      - id: go-build-repo-mod
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
      - id: go-vet-mod
  # To use commitlint pre-commit hook don't forget to install commitlint
  # npm install -g @commitlint/cli @commitlint/config-conventional
  # after that, below command to create commitlint.config.js to your root project
  # echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']